

const TOKEN_URL = process.env.TOKEN_URL;
const INSTITUTIONS_URL = process.env.INSTITUTIONS_URL
const AGREEMENT_URL = process.env.AGREEMENT_URL
const REQUISITION_URL = process.env.REQUISITION_URL

const SECRET_ID = process.env.SECRET_ID
const SECRET_KEY = process.env.SECRET_KEY

const DATABASE_URL = process.env.DATABASE_URL

const FRONTEND_URL = process.env.FRONTEND_URL

module.exports = {DATABASE_URL, TOKEN_URL, INSTITUTIONS_URL, AGREEMENT_URL, REQUISITION_URL, SECRET_ID, SECRET_KEY, FRONTEND_URL};

